//Castle.Core/5.1.1=>C:\Users\Andreas Arrgård\.nuget\packages\castle.core\5.1.1\lib\net6.0\Castle.Core.dll
//IdentityModel/6.1.0=>C:\Users\Andreas Arrgård\.nuget\packages\identitymodel\6.1.0\lib\net6.0\IdentityModel.dll
//Microsoft.ApplicationInsights/2.21.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.applicationinsights\2.21.0\lib\netstandard2.0\Microsoft.ApplicationInsights.dll
//Microsoft.ApplicationInsights.AspNetCore/2.21.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.applicationinsights.aspnetcore\2.21.0\lib\netstandard2.0\Microsoft.ApplicationInsights.AspNetCore.dll
//Microsoft.ApplicationInsights.DependencyCollector/2.21.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.applicationinsights.dependencycollector\2.21.0\lib\netstandard2.0\Microsoft.AI.DependencyCollector.dll
//Microsoft.ApplicationInsights.EventCounterCollector/2.21.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.applicationinsights.eventcountercollector\2.21.0\lib\netstandard2.0\Microsoft.AI.EventCounterCollector.dll
//Microsoft.ApplicationInsights.PerfCounterCollector/2.21.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.applicationinsights.perfcountercollector\2.21.0\lib\netstandard2.0\Microsoft.AI.PerfCounterCollector.dll
//Microsoft.ApplicationInsights.WindowsServer/2.21.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.applicationinsights.windowsserver\2.21.0\lib\netstandard2.0\Microsoft.AI.WindowsServer.dll
//Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel/2.21.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.applicationinsights.windowsserver.telemetrychannel\2.21.0\lib\netstandard2.0\Microsoft.AI.ServerTelemetryChannel.dll
//Microsoft.AspNetCore.Hosting/2.1.1=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.aspnetcore.hosting\2.1.1\lib\netstandard2.0\Microsoft.AspNetCore.Hosting.dll
//Microsoft.AspNetCore.Hosting.Abstractions/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.aspnetcore.hosting.abstractions\2.2.0\lib\netstandard2.0\Microsoft.AspNetCore.Hosting.Abstractions.dll
//Microsoft.AspNetCore.Hosting.Server.Abstractions/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.aspnetcore.hosting.server.abstractions\2.2.0\lib\netstandard2.0\Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
//Microsoft.AspNetCore.Http/2.1.22=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.aspnetcore.http\2.1.22\lib\netstandard2.0\Microsoft.AspNetCore.Http.dll
//Microsoft.AspNetCore.Http.Abstractions/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.aspnetcore.http.abstractions\2.2.0\lib\netstandard2.0\Microsoft.AspNetCore.Http.Abstractions.dll
//Microsoft.AspNetCore.Http.Extensions/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.aspnetcore.http.extensions\2.2.0\lib\netstandard2.0\Microsoft.AspNetCore.Http.Extensions.dll
//Microsoft.AspNetCore.Http.Features/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.aspnetcore.http.features\2.2.0\lib\netstandard2.0\Microsoft.AspNetCore.Http.Features.dll
//Microsoft.AspNetCore.Mvc.Versioning/5.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.aspnetcore.mvc.versioning\5.0.0\lib\net5.0\Microsoft.AspNetCore.Mvc.Versioning.dll
//Microsoft.AspNetCore.StaticFiles/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.aspnetcore.staticfiles\2.2.0\lib\netstandard2.0\Microsoft.AspNetCore.StaticFiles.dll
//Microsoft.AspNetCore.WebUtilities/2.1.1=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.aspnetcore.webutilities\2.1.1\lib\netstandard2.0\Microsoft.AspNetCore.WebUtilities.dll
//Microsoft.CodeAnalysis.Common/4.6.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.codeanalysis.common\4.6.0\lib\net6.0\Microsoft.CodeAnalysis.dll
//Microsoft.CodeAnalysis.CSharp/4.6.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.codeanalysis.csharp\4.6.0\lib\net6.0\Microsoft.CodeAnalysis.CSharp.dll
//Microsoft.CodeAnalysis.CSharp.Scripting/4.6.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.codeanalysis.csharp.scripting\4.6.0\lib\net6.0\Microsoft.CodeAnalysis.CSharp.Scripting.dll
//Microsoft.CodeAnalysis.Scripting.Common/4.6.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.codeanalysis.scripting.common\4.6.0\lib\net6.0\Microsoft.CodeAnalysis.Scripting.dll
//Microsoft.CodeCoverage/17.6.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.codecoverage\17.6.0\lib\netcoreapp3.1\Microsoft.VisualStudio.CodeCoverage.Shim.dll
//Microsoft.CSharp/4.7.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.csharp\4.7.0\ref\netcoreapp2.0\_._
//Microsoft.Extensions.Caching.Abstractions/1.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.caching.abstractions\1.0.0\lib\netstandard1.0\Microsoft.Extensions.Caching.Abstractions.dll
//Microsoft.Extensions.Caching.Memory/1.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.caching.memory\1.0.0\lib\netstandard1.3\Microsoft.Extensions.Caching.Memory.dll
//Microsoft.Extensions.Configuration/7.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.configuration\7.0.0\lib\net7.0\Microsoft.Extensions.Configuration.dll
//Microsoft.Extensions.Configuration.Abstractions/7.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.configuration.abstractions\7.0.0\lib\net7.0\Microsoft.Extensions.Configuration.Abstractions.dll
//Microsoft.Extensions.Configuration.Binder/7.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.configuration.binder\7.0.0\lib\net7.0\Microsoft.Extensions.Configuration.Binder.dll
//Microsoft.Extensions.Configuration.EnvironmentVariables/2.1.1=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.configuration.environmentvariables\2.1.1\lib\netstandard2.0\Microsoft.Extensions.Configuration.EnvironmentVariables.dll
//Microsoft.Extensions.Configuration.FileExtensions/3.1.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.configuration.fileextensions\3.1.0\lib\netcoreapp3.1\Microsoft.Extensions.Configuration.FileExtensions.dll
//Microsoft.Extensions.Configuration.Json/3.1.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.configuration.json\3.1.0\lib\netcoreapp3.1\Microsoft.Extensions.Configuration.Json.dll
//Microsoft.Extensions.DependencyInjection/7.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.dependencyinjection\7.0.0\lib\net7.0\Microsoft.Extensions.DependencyInjection.dll
//Microsoft.Extensions.DependencyInjection.Abstractions/7.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\7.0.0\lib\net7.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll
//Microsoft.Extensions.FileProviders.Abstractions/3.1.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.fileproviders.abstractions\3.1.0\lib\netcoreapp3.1\Microsoft.Extensions.FileProviders.Abstractions.dll
//Microsoft.Extensions.FileProviders.Physical/3.1.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.fileproviders.physical\3.1.0\lib\netcoreapp3.1\Microsoft.Extensions.FileProviders.Physical.dll
//Microsoft.Extensions.FileSystemGlobbing/3.1.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.filesystemglobbing\3.1.0\lib\netstandard2.0\Microsoft.Extensions.FileSystemGlobbing.dll
//Microsoft.Extensions.Hosting.Abstractions/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.hosting.abstractions\2.2.0\lib\netstandard2.0\Microsoft.Extensions.Hosting.Abstractions.dll
//Microsoft.Extensions.Http/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.http\2.2.0\lib\netstandard2.0\Microsoft.Extensions.Http.dll
//Microsoft.Extensions.Logging/7.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.logging\7.0.0\lib\net7.0\Microsoft.Extensions.Logging.dll
//Microsoft.Extensions.Logging.Abstractions/7.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.logging.abstractions\7.0.0\lib\net7.0\Microsoft.Extensions.Logging.Abstractions.dll
//Microsoft.Extensions.Logging.ApplicationInsights/2.21.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.logging.applicationinsights\2.21.0\lib\netstandard2.0\Microsoft.Extensions.Logging.ApplicationInsights.dll
//Microsoft.Extensions.Logging.Configuration/7.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.logging.configuration\7.0.0\lib\net7.0\Microsoft.Extensions.Logging.Configuration.dll
//Microsoft.Extensions.Logging.Console/7.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.logging.console\7.0.0\lib\net7.0\Microsoft.Extensions.Logging.Console.dll
//Microsoft.Extensions.ObjectPool/2.1.1=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.objectpool\2.1.1\lib\netstandard2.0\Microsoft.Extensions.ObjectPool.dll
//Microsoft.Extensions.Options/7.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.options\7.0.0\lib\net7.0\Microsoft.Extensions.Options.dll
//Microsoft.Extensions.Options.ConfigurationExtensions/7.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.options.configurationextensions\7.0.0\lib\net7.0\Microsoft.Extensions.Options.ConfigurationExtensions.dll
//Microsoft.Extensions.Primitives/7.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.primitives\7.0.0\lib\net7.0\Microsoft.Extensions.Primitives.dll
//Microsoft.Extensions.WebEncoders/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.webencoders\2.2.0\lib\netstandard2.0\Microsoft.Extensions.WebEncoders.dll
//Microsoft.IdentityModel.Abstractions/6.30.1=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.identitymodel.abstractions\6.30.1\lib\net6.0\Microsoft.IdentityModel.Abstractions.dll
//Microsoft.IdentityModel.JsonWebTokens/6.30.1=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.identitymodel.jsonwebtokens\6.30.1\lib\net6.0\Microsoft.IdentityModel.JsonWebTokens.dll
//Microsoft.IdentityModel.Logging/6.30.1=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.identitymodel.logging\6.30.1\lib\net6.0\Microsoft.IdentityModel.Logging.dll
//Microsoft.IdentityModel.Tokens/6.30.1=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.identitymodel.tokens\6.30.1\lib\net6.0\Microsoft.IdentityModel.Tokens.dll
//Microsoft.Net.Http.Headers/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.net.http.headers\2.2.0\lib\netstandard2.0\Microsoft.Net.Http.Headers.dll
//Microsoft.NET.Test.Sdk/17.6.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.net.test.sdk\17.6.0\lib\netcoreapp3.1\_._
//Microsoft.NETCore.Platforms/3.1.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.netcore.platforms\3.1.0\lib\netstandard1.0\_._
//Microsoft.NETCore.Targets/1.1.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.netcore.targets\1.1.0\lib\netstandard1.0\_._
//Microsoft.OpenApi/1.2.3=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.openapi\1.2.3\lib\netstandard2.0\Microsoft.OpenApi.dll
//Microsoft.TestPlatform.ObjectModel/17.6.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.testplatform.objectmodel\17.6.0\lib\netcoreapp3.1\Microsoft.TestPlatform.CoreUtilities.dll
//Microsoft.TestPlatform.TestHost/17.6.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.testplatform.testhost\17.6.0\lib\netcoreapp3.1\Microsoft.TestPlatform.CommunicationUtilities.dll
//Microsoft.Win32.Registry/4.7.0=>
//Microsoft.Win32.SystemEvents/4.7.0=>
//Moq/4.18.4=>C:\Users\Andreas Arrgård\.nuget\packages\moq\4.18.4\lib\net6.0\Moq.dll
//NETStandard.Library/2.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\netstandard.library\2.0.0\lib\netstandard1.0\_._
//Newtonsoft.Json/13.0.3=>C:\Users\Andreas Arrgård\.nuget\packages\newtonsoft.json\13.0.3\lib\net6.0\Newtonsoft.Json.dll
//NuGet.Frameworks/5.11.0=>C:\Users\Andreas Arrgård\.nuget\packages\nuget.frameworks\5.11.0\lib\netstandard2.0\NuGet.Frameworks.dll
//NUnit/3.13.3=>C:\Users\Andreas Arrgård\.nuget\packages\nunit\3.13.3\lib\netstandard2.0\nunit.framework.dll
//SharpZipLib/1.4.2=>C:\Users\Andreas Arrgård\.nuget\packages\sharpziplib\1.4.2\lib\net6.0\ICSharpCode.SharpZipLib.dll
//SolidCI.Azure/1.0.1=>C:\Users\Andreas Arrgård\.nuget\packages\solidci.azure\1.0.1\lib\netstandard2.0\SolidCI.Azure.dll
//SolidProxy.Core/1.0.0-rc023=>C:\Users\Andreas Arrgård\.nuget\packages\solidproxy.core\1.0.0-rc023\lib\netstandard2.0\SolidProxy.Core.dll
//SolidProxy.GeneratorCastle/1.0.0-rc023=>C:\Users\Andreas Arrgård\.nuget\packages\solidproxy.generatorcastle\1.0.0-rc023\lib\netstandard2.0\SolidProxy.GeneratorCastle.dll
//SolidProxy.MicrosoftDI/1.0.0-rc022=>C:\Users\Andreas Arrgård\.nuget\packages\solidproxy.microsoftdi\1.0.0-rc022\lib\netstandard2.0\SolidProxy.MicrosoftDI.dll
//Swashbuckle.AspNetCore.Swagger/6.5.0=>C:\Users\Andreas Arrgård\.nuget\packages\swashbuckle.aspnetcore.swagger\6.5.0\lib\net7.0\Swashbuckle.AspNetCore.Swagger.dll
//Swashbuckle.AspNetCore.SwaggerGen/6.5.0=>C:\Users\Andreas Arrgård\.nuget\packages\swashbuckle.aspnetcore.swaggergen\6.5.0\lib\net7.0\Swashbuckle.AspNetCore.SwaggerGen.dll
//Swashbuckle.AspNetCore.SwaggerUI/6.5.0=>C:\Users\Andreas Arrgård\.nuget\packages\swashbuckle.aspnetcore.swaggerui\6.5.0\lib\net7.0\Swashbuckle.AspNetCore.SwaggerUI.dll
//System.Buffers/4.5.0=>C:\Users\Andreas Arrgård\.nuget\packages\system.buffers\4.5.0\ref\netcoreapp2.0\_._
//System.Collections/4.0.11=>C:\Users\Andreas Arrgård\.nuget\packages\system.collections\4.0.11\ref\netstandard1.3\System.Collections.dll
//System.Collections.Immutable/7.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\system.collections.immutable\7.0.0\lib\net7.0\System.Collections.Immutable.dll
//System.Configuration.ConfigurationManager/4.7.0=>
//System.Diagnostics.Debug/4.0.11=>
//System.Diagnostics.DiagnosticSource/5.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\system.diagnostics.diagnosticsource\5.0.0\lib\net5.0\System.Diagnostics.DiagnosticSource.dll
//System.Diagnostics.EventLog/6.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\system.diagnostics.eventlog\6.0.0\lib\net6.0\System.Diagnostics.EventLog.dll
//System.Diagnostics.PerformanceCounter/4.7.0=>C:\Users\Andreas Arrgård\.nuget\packages\system.diagnostics.performancecounter\4.7.0\ref\netstandard2.0\System.Diagnostics.PerformanceCounter.dll
//System.Drawing.Common/4.7.0=>
//System.Globalization/4.0.11=>
//System.IdentityModel.Tokens.Jwt/6.30.1=>C:\Users\Andreas Arrgård\.nuget\packages\system.identitymodel.tokens.jwt\6.30.1\lib\net6.0\System.IdentityModel.Tokens.Jwt.dll
//System.IO/4.1.0=>
//System.IO.FileSystem.AccessControl/4.7.0=>C:\Users\Andreas Arrgård\.nuget\packages\system.io.filesystem.accesscontrol\4.7.0\ref\netstandard2.0\System.IO.FileSystem.AccessControl.dll
//System.Linq/4.1.0=>C:\Users\Andreas Arrgård\.nuget\packages\system.linq\4.1.0\ref\netstandard1.6\System.Linq.dll
//System.Reflection/4.1.0=>
//System.Reflection.Metadata/7.0.1=>C:\Users\Andreas Arrgård\.nuget\packages\system.reflection.metadata\7.0.1\lib\net7.0\System.Reflection.Metadata.dll
//System.Reflection.Primitives/4.0.1=>
//System.Resources.ResourceManager/4.0.1=>
//System.Runtime/4.3.0=>C:\Users\Andreas Arrgård\.nuget\packages\system.runtime\4.3.0\ref\netstandard1.5\System.Runtime.dll
//System.Runtime.CompilerServices.Unsafe/6.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\system.runtime.compilerservices.unsafe\6.0.0\lib\net6.0\System.Runtime.CompilerServices.Unsafe.dll
//System.Runtime.Extensions/4.1.0=>
//System.Security.AccessControl/4.7.0=>C:\Users\Andreas Arrgård\.nuget\packages\system.security.accesscontrol\4.7.0\ref\netstandard2.0\System.Security.AccessControl.dll
//System.Security.Cryptography.Cng/4.5.0=>C:\Users\Andreas Arrgård\.nuget\packages\system.security.cryptography.cng\4.5.0\ref\netcoreapp2.1\System.Security.Cryptography.Cng.dll
//System.Security.Cryptography.ProtectedData/4.7.0=>
//System.Security.Permissions/4.7.0=>
//System.Security.Principal.Windows/4.7.0=>C:\Users\Andreas Arrgård\.nuget\packages\system.security.principal.windows\4.7.0\ref\netcoreapp3.0\System.Security.Principal.Windows.dll
//System.Text.Encoding/4.3.0=>C:\Users\Andreas Arrgård\.nuget\packages\system.text.encoding\4.3.0\ref\netstandard1.3\System.Text.Encoding.dll
//System.Text.Encoding.CodePages/7.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\system.text.encoding.codepages\7.0.0\lib\net7.0\System.Text.Encoding.CodePages.dll
//System.Text.Encodings.Web/7.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\system.text.encodings.web\7.0.0\lib\net7.0\System.Text.Encodings.Web.dll
//System.Text.Json/7.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\system.text.json\7.0.0\lib\net7.0\System.Text.Json.dll
//System.Threading/4.0.11=>C:\Users\Andreas Arrgård\.nuget\packages\system.threading\4.0.11\ref\netstandard1.3\System.Threading.dll
//System.Threading.Tasks/4.0.11=>C:\Users\Andreas Arrgård\.nuget\packages\system.threading.tasks\4.0.11\ref\netstandard1.3\System.Threading.Tasks.dll
//System.Windows.Extensions/4.7.0=>
//WindowsAzure.Storage/9.3.3=>C:\Users\Andreas Arrgård\.nuget\packages\windowsazure.storage\9.3.3\lib\netstandard1.3\Microsoft.WindowsAzure.Storage.dll
//SolidRpc.Abstractions/1.0.0=>C:\Development\github\solidrpc\SolidRpc.Abstractions\bin\Debug\netstandard2.0\SolidRpc.Abstractions.dll
//SolidRpc.Node/1.0.0=>C:\Development\github\solidrpc\SolidRpc.Node\bin\Debug\netstandard2.0\SolidRpc.Node.dll
//SolidRpc.OpenApi.ApplicationInsights/1.0.0=>C:\Development\github\solidrpc\SolidRpc.OpenApi.ApplicationInsights\bin\Debug\netstandard2.0\SolidRpc.OpenApi.ApplicationInsights.dll
//SolidRpc.OpenApi.AspNetCore/1.0.0=>C:\Development\github\solidrpc\SolidRpc.OpenApi.AspNetCore\bin\Debug\netstandard2.0\SolidRpc.OpenApi.AspNetCore.dll
//SolidRpc.OpenApi.AzQueue/1.0.0=>C:\Development\github\solidrpc\SolidRpc.OpenApi.AzQueue\bin\Debug\netstandard2.0\SolidRpc.OpenApi.AzQueue.dll
//SolidRpc.OpenApi.Binder/1.0.0=>C:\Development\github\solidrpc\SolidRpc.OpenApi.Binder\bin\Debug\netstandard2.0\SolidRpc.OpenApi.Binder.dll
//SolidRpc.OpenApi.DotNetTool/1.0.0=>not:bin/placeholder/SolidRpc.OpenApi.DotNetTool.dll
//SolidRpc.OpenApi.Generator/1.0.0=>C:\Development\github\solidrpc\SolidRpc.OpenApi.Generator\bin\Debug\netstandard2.0\SolidRpc.OpenApi.Generator.dll
//SolidRpc.OpenApi.Generator.Impl/1.0.0=>C:\Development\github\solidrpc\SolidRpc.OpenApi.Generator.Impl\bin\Debug\netstandard2.0\SolidRpc.OpenApi.Generator.Impl.dll
//SolidRpc.OpenApi.Model/1.0.0=>C:\Development\github\solidrpc\SolidRpc.OpenApi.Model\bin\Debug\netstandard2.0\SolidRpc.OpenApi.Model.dll
//SolidRpc.OpenApi.OAuth2/1.0.0=>C:\Development\github\solidrpc\SolidRpc.OpenApi.OAuth2\bin\Debug\netstandard2.0\SolidRpc.OpenApi.OAuth2.dll
//SolidRpc.OpenApi.SwaggerUI/1.0.0=>C:\Development\github\solidrpc\SolidRpc.OpenApi.SwaggerUI\bin\Debug\netstandard2.0\SolidRpc.OpenApi.SwaggerUI.dll
//SolidRpc.Test.Petstore/1.4.5=>C:\Development\github\solidrpc\SolidRpc.Test.Petstore\bin\Debug\netstandard2.0\SolidRpc.Test.Petstore.dll
//Generating stubs for : C:\Development\github\solidrpc\SolidRpc.Abstractions\bin\Debug\netstandard2.0\SolidRpc.Abstractions.dll
//Generating stubs for : C:\Development\github\solidrpc\SolidRpc.OpenApi.Generator\bin\Debug\netstandard2.0\SolidRpc.OpenApi.Generator.dll
//Generating stubs for : C:\Development\github\solidrpc\SolidRpc.OpenApi.SwaggerUI\bin\Debug\netstandard2.0\SolidRpc.OpenApi.SwaggerUI.dll
//Generating stubs for : C:\Development\github\solidrpc\SolidRpc.Test.Petstore\bin\Debug\netstandard2.0\SolidRpc.Test.Petstore.dll
