using Newtonsoft.Json;
using SolidRpc.OpenApi.AzFunctions.Functions.Model;
using System;
using System.IO;
using System.Linq;

namespace SolidRpc.OpenApi.AzFunctions.Functions.Impl
{
    /// <summary>
    /// Base class for the functions
    /// </summary>
    public abstract class AzFunction : IAzFunction
    {
        private string functionName;

        /// <summary>
        /// Constructs a new instance
        /// </summary>
        /// <param name="functionHandler"></param>
        /// <param name="functionName"></param>
        /// <param name="function"></param>
        public AzFunction(IAzFunctionHandler functionHandler, string functionName, Function function)
        {
            FunctionHandler = functionHandler;
            Name = functionName;
            Function = function;
        }

        protected AzFunction(IAzFunctionHandler functionHandler, string functionName)
        {
            FunctionHandler = functionHandler;
            this.functionName = functionName;
        }

        /// <summary>
        /// The trigger type
        /// </summary>
        public abstract string TriggerType { get; }

        /// <summary>
        /// The function handler
        /// </summary>
        public IAzFunctionHandler FunctionHandler { get; }

        /// <summary>
        /// The name of the function
        /// </summary>
        public string Name { get; }

        /// <summary>
        /// The function
        /// </summary>
        public Function Function { get; set; }

        /// <summary>
        /// The trigger binding
        /// </summary>
        public Binding TriggerBinding => Function.Bindings.Single(o => o.Type == TriggerType);

        /// <summary>
        /// The function
        /// </summary>
        public string FunctionJson {
            get
            {
                return SerializeFunctionJson(Function);
            }
            set
            {
                Function = DeserializeFunction(value);
            }
        }

        /// <summary>
        /// Returns the generated by tag.
        /// </summary>
        public string GeneratedBy => Function.GeneratedBy;

        private Function DeserializeFunction(string value)
        {
            return JsonConvert.DeserializeObject<Function>(value);
        }

        private string SerializeFunctionJson(Function function)
        {
            var sw = new StringWriter();
            using (JsonWriter writer = new JsonTextWriter(sw))
            {
                var settings = new JsonSerializerSettings()
                {
                    ContractResolver = NewtonsoftContractResolver.Instance,
                    Formatting = Formatting.Indented
                };
                var serializer = JsonSerializer.Create(settings);
                serializer.Serialize(writer, function);
            }
            return sw.ToString();
        }

        private string ReadFunctionJson()
        {
            return ReadFunctionJson(new FileInfo(Path.Combine(FunctionHandler.BaseDir.FullName, Name, "function.json")));
        }

        private string ReadFunctionJson(FileInfo fi)
        {
            if(!fi.Exists)
            {
                return "";
            }
            using (var tr = fi.OpenText())
            {
                return tr.ReadToEnd();
            }
        }

        private void WriteFunctionJson()
        {
            WriteFunctionJson(new FileInfo(Path.Combine(FunctionHandler.BaseDir.FullName, Name, "function.json")));
            if(FunctionHandler.DevDir != null)
            {
                WriteFunctionJson(new FileInfo(Path.Combine(FunctionHandler.DevDir.FullName, Name, "function.json")));
            }
        }

        private void WriteFunctionJson(FileInfo fi)
        {
            using (var tw = fi.CreateText())
            {
                tw.Write(SerializeFunctionJson(Function));
            }
            var projectDir = fi.Directory?.Parent?.Parent?.Parent?.Parent;
            if(projectDir == null || !projectDir.Exists)
            {
                return;
            }
            var projectHostFile = new FileInfo(Path.Combine(projectDir.FullName, "host.json"));
            if(projectHostFile.Exists)
            {

            }
        }

        /// <summary>
        /// Deletes the function
        /// </summary>
        public void Delete()
        {
            new DirectoryInfo(Path.Combine(FunctionHandler.BaseDir.FullName, Name)).Delete(true);
            if (FunctionHandler.DevDir != null)
            {
                new DirectoryInfo(Path.Combine(FunctionHandler.DevDir.FullName, Name)).Delete(true);
            }
        }

        /// <summary>
        /// Saves the run.csx and function.json files
        /// </summary>
        public bool Save()
        {
            if (FunctionHandler.DevDir != null)
            {
                Save(new FileInfo(Path.Combine(FunctionHandler.DevDir.FullName, Name, "function.json")));
            }
            return Save(new FileInfo(Path.Combine(FunctionHandler.BaseDir.FullName, Name, "function.json")));
        }
        /// <summary>
        /// Saves the run.csx and function.json files
        /// </summary>
        public bool Save(FileInfo fi)
        {
            if (!fi.Directory.Exists)
            {
                fi.Directory.Create();
            }
            if(false==string.Equals(FunctionJson, SerializeFunctionJson(DeserializeFunction(ReadFunctionJson(fi)))))
            {
                WriteFunctionJson(fi);
                return true;
            }
            return false;
        }
    }
}
