//Microsoft.CodeAnalysis.Common/4.8.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.codeanalysis.common\4.8.0\lib\net6.0\Microsoft.CodeAnalysis.dll
//Microsoft.CodeAnalysis.CSharp/4.8.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.codeanalysis.csharp\4.8.0\lib\net6.0\Microsoft.CodeAnalysis.CSharp.dll
//Microsoft.CodeAnalysis.CSharp.Scripting/4.8.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.codeanalysis.csharp.scripting\4.8.0\lib\net6.0\Microsoft.CodeAnalysis.CSharp.Scripting.dll
//Microsoft.CodeAnalysis.Scripting.Common/4.8.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.codeanalysis.scripting.common\4.8.0\lib\net6.0\Microsoft.CodeAnalysis.Scripting.dll
//Microsoft.CodeCoverage/17.8.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.codecoverage\17.8.0\lib\netcoreapp3.1\Microsoft.VisualStudio.CodeCoverage.Shim.dll
//Microsoft.CSharp/4.7.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.csharp\4.7.0\ref\netcoreapp2.0\_._
//Microsoft.Extensions.Configuration/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.configuration\2.2.0\lib\netstandard2.0\Microsoft.Extensions.Configuration.dll
//Microsoft.Extensions.Configuration.Abstractions/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.configuration.abstractions\2.2.0\lib\netstandard2.0\Microsoft.Extensions.Configuration.Abstractions.dll
//Microsoft.Extensions.Configuration.Binder/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.configuration.binder\2.2.0\lib\netstandard2.0\Microsoft.Extensions.Configuration.Binder.dll
//Microsoft.Extensions.DependencyInjection/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.dependencyinjection\2.2.0\lib\netcoreapp2.0\Microsoft.Extensions.DependencyInjection.dll
//Microsoft.Extensions.DependencyInjection.Abstractions/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\2.2.0\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll
//Microsoft.Extensions.Http/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.http\2.2.0\lib\netstandard2.0\Microsoft.Extensions.Http.dll
//Microsoft.Extensions.Logging/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.logging\2.2.0\lib\netstandard2.0\Microsoft.Extensions.Logging.dll
//Microsoft.Extensions.Logging.Abstractions/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.logging.abstractions\2.2.0\lib\netstandard2.0\Microsoft.Extensions.Logging.Abstractions.dll
//Microsoft.Extensions.Options/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.options\2.2.0\lib\netstandard2.0\Microsoft.Extensions.Options.dll
//Microsoft.Extensions.Primitives/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.primitives\2.2.0\lib\netstandard2.0\Microsoft.Extensions.Primitives.dll
//Microsoft.NET.Test.Sdk/17.8.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.net.test.sdk\17.8.0\lib\netcoreapp3.1\_._
//Microsoft.NETCore.Platforms/1.1.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.netcore.platforms\1.1.0\lib\netstandard1.0\_._
//Microsoft.TestPlatform.ObjectModel/17.8.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.testplatform.objectmodel\17.8.0\lib\netcoreapp3.1\Microsoft.TestPlatform.CoreUtilities.dll
//Microsoft.TestPlatform.TestHost/17.8.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.testplatform.testhost\17.8.0\lib\netcoreapp3.1\Microsoft.TestPlatform.CommunicationUtilities.dll
//NETStandard.Library/2.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\netstandard.library\2.0.0\lib\netstandard1.0\_._
//Newtonsoft.Json/13.0.3=>C:\Users\Andreas Arrgård\.nuget\packages\newtonsoft.json\13.0.3\lib\net6.0\Newtonsoft.Json.dll
//NuGet.Frameworks/6.5.0=>C:\Users\Andreas Arrgård\.nuget\packages\nuget.frameworks\6.5.0\lib\netstandard2.0\NuGet.Frameworks.dll
//NUnit/3.13.3=>C:\Users\Andreas Arrgård\.nuget\packages\nunit\3.13.3\lib\netstandard2.0\nunit.framework.dll
//SharpZipLib/1.4.2=>C:\Users\Andreas Arrgård\.nuget\packages\sharpziplib\1.4.2\lib\net6.0\ICSharpCode.SharpZipLib.dll
//SolidProxy.Core/1.0.0-rc025=>C:\Users\Andreas Arrgård\.nuget\packages\solidproxy.core\1.0.0-rc025\lib\netstandard2.0\SolidProxy.Core.dll
//SolidProxy.MicrosoftDI/1.0.0-rc024=>C:\Users\Andreas Arrgård\.nuget\packages\solidproxy.microsoftdi\1.0.0-rc024\lib\netstandard2.0\SolidProxy.MicrosoftDI.dll
//System.Collections.Immutable/8.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\system.collections.immutable\8.0.0\lib\net6.0\System.Collections.Immutable.dll
//System.ComponentModel.Annotations/4.5.0=>C:\Users\Andreas Arrgård\.nuget\packages\system.componentmodel.annotations\4.5.0\ref\netcoreapp2.0\_._
//System.Memory/4.5.1=>C:\Users\Andreas Arrgård\.nuget\packages\system.memory\4.5.1\ref\netcoreapp2.1\_._
//System.Reflection.Metadata/8.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\system.reflection.metadata\8.0.0\lib\net6.0\System.Reflection.Metadata.dll
//System.Runtime.CompilerServices.Unsafe/6.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\system.runtime.compilerservices.unsafe\6.0.0\lib\net6.0\System.Runtime.CompilerServices.Unsafe.dll
//SolidRpc.Abstractions/1.0.0=>C:\Development\github\solidrpc\SolidRpc.Abstractions\bin\Debug\netstandard2.0\SolidRpc.Abstractions.dll
//SolidRpc.OpenApi.Binder/1.0.0=>C:\Development\github\solidrpc\SolidRpc.OpenApi.Binder\bin\Debug\netstandard2.0\SolidRpc.OpenApi.Binder.dll
//SolidRpc.OpenApi.DotNetTool/1.0.0=>not:bin/placeholder/SolidRpc.OpenApi.DotNetTool.dll
//SolidRpc.OpenApi.Generator/1.0.0=>C:\Development\github\solidrpc\SolidRpc.OpenApi.Generator\bin\Debug\netstandard2.0\SolidRpc.OpenApi.Generator.dll
//SolidRpc.OpenApi.Generator.Impl/1.0.0=>C:\Development\github\solidrpc\SolidRpc.OpenApi.Generator.Impl\bin\Debug\netstandard2.0\SolidRpc.OpenApi.Generator.Impl.dll
//SolidRpc.OpenApi.Model/1.0.0=>C:\Development\github\solidrpc\SolidRpc.OpenApi.Model\bin\Debug\netstandard2.0\SolidRpc.OpenApi.Model.dll
//Generating stubs for : C:\Development\github\solidrpc\SolidRpc.Abstractions\bin\Debug\netstandard2.0\SolidRpc.Abstractions.dll
//Generating stubs for : C:\Development\github\solidrpc\SolidRpc.OpenApi.Generator\bin\Debug\netstandard2.0\SolidRpc.OpenApi.Generator.dll
