//Microsoft.ApplicationInsights/2.23.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.applicationinsights\2.23.0\lib\netstandard2.0\Microsoft.ApplicationInsights.dll
//Microsoft.CodeAnalysis.Common/5.3.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.codeanalysis.common\5.3.0\lib\net9.0\Microsoft.CodeAnalysis.dll
//Microsoft.CodeAnalysis.CSharp/5.3.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.codeanalysis.csharp\5.3.0\lib\net9.0\Microsoft.CodeAnalysis.CSharp.dll
//Microsoft.CodeAnalysis.CSharp.Scripting/5.3.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.codeanalysis.csharp.scripting\5.3.0\lib\net9.0\Microsoft.CodeAnalysis.CSharp.Scripting.dll
//Microsoft.CodeAnalysis.Scripting.Common/5.3.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.codeanalysis.scripting.common\5.3.0\lib\net9.0\Microsoft.CodeAnalysis.Scripting.dll
//Microsoft.CodeCoverage/18.6.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.codecoverage\18.6.0\lib\net8.0\Microsoft.VisualStudio.CodeCoverage.Shim.dll
//Microsoft.Extensions.Configuration/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.configuration\2.2.0\lib\netstandard2.0\Microsoft.Extensions.Configuration.dll
//Microsoft.Extensions.Configuration.Abstractions/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.configuration.abstractions\2.2.0\lib\netstandard2.0\Microsoft.Extensions.Configuration.Abstractions.dll
//Microsoft.Extensions.Configuration.Binder/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.configuration.binder\2.2.0\lib\netstandard2.0\Microsoft.Extensions.Configuration.Binder.dll
//Microsoft.Extensions.DependencyInjection/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.dependencyinjection\2.2.0\lib\netcoreapp2.0\Microsoft.Extensions.DependencyInjection.dll
//Microsoft.Extensions.DependencyInjection.Abstractions/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\2.2.0\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll
//Microsoft.Extensions.DependencyModel/8.0.2=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.dependencymodel\8.0.2\lib\net8.0\Microsoft.Extensions.DependencyModel.dll
//Microsoft.Extensions.Http/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.http\2.2.0\lib\netstandard2.0\Microsoft.Extensions.Http.dll
//Microsoft.Extensions.Logging/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.logging\2.2.0\lib\netstandard2.0\Microsoft.Extensions.Logging.dll
//Microsoft.Extensions.Logging.Abstractions/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.logging.abstractions\2.2.0\lib\netstandard2.0\Microsoft.Extensions.Logging.Abstractions.dll
//Microsoft.Extensions.Options/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.options\2.2.0\lib\netstandard2.0\Microsoft.Extensions.Options.dll
//Microsoft.Extensions.Primitives/2.2.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.extensions.primitives\2.2.0\lib\netstandard2.0\Microsoft.Extensions.Primitives.dll
//Microsoft.NET.Test.Sdk/18.6.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.net.test.sdk\18.6.0\lib\net8.0\_._
//Microsoft.Testing.Extensions.Telemetry/2.1.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.testing.extensions.telemetry\2.1.0\lib\net9.0\Microsoft.Testing.Extensions.Telemetry.dll
//Microsoft.Testing.Extensions.TrxReport.Abstractions/2.1.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.testing.extensions.trxreport.abstractions\2.1.0\lib\net9.0\Microsoft.Testing.Extensions.TrxReport.Abstractions.dll
//Microsoft.Testing.Extensions.VSTestBridge/2.1.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.testing.extensions.vstestbridge\2.1.0\lib\net9.0\Microsoft.Testing.Extensions.VSTestBridge.dll
//Microsoft.Testing.Platform/2.1.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.testing.platform\2.1.0\lib\net9.0\Microsoft.Testing.Platform.dll
//Microsoft.Testing.Platform.MSBuild/2.1.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.testing.platform.msbuild\2.1.0\lib\net9.0\Microsoft.Testing.Extensions.MSBuild.dll
//Microsoft.TestPlatform.ObjectModel/18.6.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.testplatform.objectmodel\18.6.0\lib\net8.0\Microsoft.TestPlatform.CoreUtilities.dll
//Microsoft.TestPlatform.TestHost/18.6.0=>C:\Users\Andreas Arrgård\.nuget\packages\microsoft.testplatform.testhost\18.6.0\lib\net8.0\Microsoft.TestPlatform.CommunicationUtilities.dll
//Newtonsoft.Json/13.0.4=>C:\Users\Andreas Arrgård\.nuget\packages\newtonsoft.json\13.0.4\lib\net6.0\Newtonsoft.Json.dll
//NUnit/4.6.1=>C:\Users\Andreas Arrgård\.nuget\packages\nunit\4.6.1\lib\net8.0\nunit.framework.dll
//SharpZipLib/1.4.2=>C:\Users\Andreas Arrgård\.nuget\packages\sharpziplib\1.4.2\lib\net6.0\ICSharpCode.SharpZipLib.dll
//SolidProxy.Core/1.0.0-rc025=>C:\Users\Andreas Arrgård\.nuget\packages\solidproxy.core\1.0.0-rc025\lib\netstandard2.0\SolidProxy.Core.dll
//SolidProxy.MicrosoftDI/1.0.0-rc024=>C:\Users\Andreas Arrgård\.nuget\packages\solidproxy.microsoftdi\1.0.0-rc024\lib\netstandard2.0\SolidProxy.MicrosoftDI.dll
//System.Collections.Immutable/10.0.8=>C:\Users\Andreas Arrgård\.nuget\packages\system.collections.immutable\10.0.8\lib\net9.0\System.Collections.Immutable.dll
//System.ComponentModel.Annotations/4.5.0=>C:\Users\Andreas Arrgård\.nuget\packages\system.componentmodel.annotations\4.5.0\ref\netcoreapp2.0\_._
//System.Diagnostics.DiagnosticSource/5.0.0=>C:\Users\Andreas Arrgård\.nuget\packages\system.diagnostics.diagnosticsource\5.0.0\lib\net5.0\System.Diagnostics.DiagnosticSource.dll
//System.Memory/4.5.1=>C:\Users\Andreas Arrgård\.nuget\packages\system.memory\4.5.1\ref\netcoreapp2.1\_._
//System.Reflection.Metadata/10.0.8=>C:\Users\Andreas Arrgård\.nuget\packages\system.reflection.metadata\10.0.8\lib\net9.0\System.Reflection.Metadata.dll
//System.Runtime.CompilerServices.Unsafe/4.5.1=>C:\Users\Andreas Arrgård\.nuget\packages\system.runtime.compilerservices.unsafe\4.5.1\ref\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll
//SolidRpc.Abstractions/1.0.0=>C:\Development\github\solidrpc\SolidRpc.Abstractions\bin\Debug\netstandard2.0\SolidRpc.Abstractions.dll
//SolidRpc.OpenApi.Binder/1.0.0=>C:\Development\github\solidrpc\SolidRpc.OpenApi.Binder\bin\Debug\netstandard2.0\SolidRpc.OpenApi.Binder.dll
//SolidRpc.OpenApi.DotNetTool/1.0.0=>not:bin/placeholder/SolidRpc.OpenApi.DotNetTool.dll
//SolidRpc.OpenApi.Generator/1.0.0=>C:\Development\github\solidrpc\SolidRpc.OpenApi.Generator\bin\Debug\netstandard2.0\SolidRpc.OpenApi.Generator.dll
//SolidRpc.OpenApi.Generator.Impl/1.0.0=>C:\Development\github\solidrpc\SolidRpc.OpenApi.Generator.Impl\bin\Debug\netstandard2.0\SolidRpc.OpenApi.Generator.Impl.dll
//SolidRpc.OpenApi.Model/1.0.0=>C:\Development\github\solidrpc\SolidRpc.OpenApi.Model\bin\Debug\netstandard2.0\SolidRpc.OpenApi.Model.dll
//Generating stubs for : C:\Development\github\solidrpc\SolidRpc.Abstractions\bin\Debug\netstandard2.0\SolidRpc.Abstractions.dll
//Generating stubs for : C:\Development\github\solidrpc\SolidRpc.OpenApi.Generator\bin\Debug\netstandard2.0\SolidRpc.OpenApi.Generator.dll
